name: Maintain GitHub Gists
run-name: Maintain Gists run by ${{ github.actor }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      input_path:
        description: 'Path to the input JSON file'
        required: true
        default: 'all-gists.json'
        type: string
      output_path:
        description: 'Path to the output JSON file (optional)'
        required: false
        default: 'all-gists.json'
        type: string
      skip_existing:
        description: 'Skip items that already contain a gist_id'
        required: false
        default: true
        type: boolean
      dry_run:
        description: 'Show what would be done without making API calls'
        required: false
        default: false
        type: boolean
      debug:
        description: 'Enable debug output'
        required: false
        default: false
        type: boolean

jobs:
  maintain-gists:
    name: Maintain Gists
    runs-on: ubuntu-latest

    # Prevent overlapping runs of THIS workflow on the same branch
    concurrency:
      group: maintain-gists-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script (maintain_gists.py)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GIST_TOKEN }}
        working-directory: ${{ github.workspace }}/gist-factory
        run: |
          python maintain_gists.py \
            --input "${{ inputs.input_path }}" \
            ${{ inputs.output_path && format('--output "{0}"', inputs.output_path) || '' }} \
            ${{ inputs.skip_existing && '--skip-existing' || '' }} \
            ${{ inputs.dry_run && '--dry-run' || '' }} \
            ${{ inputs.debug && '--debug' || '' }}

      - name: Commit and push changes to temp branch
        working-directory: ${{ github.workspace }}/gist-factory
        run: |
          ls -lR 
          echo "========== gist-operation-report.json ==================="
          cat gist-operation-report.json|jq
          echo "========== all-gists.json ==============================="
          cat all-gists.json
          echo "==========  configure git ==============================="
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="temp/run-${{ github.run_id }}"
          git checkout -b "$BRANCH_NAME"

          git add -A .
          if ! git diff --cached --quiet; then
            git commit -m "Update gist JSON files (run ${{ github.run_id }})"
            git push origin "$BRANCH_NAME"
          else
            echo "No changes to commit"
          fi

